name: 빌드 테스트

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Login to Github Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository.owner }}
        password: ${{ secrets.TOKEN }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: ghcr.io/@{{github.repository.owner}}/test:latest
        secrets:  |
          GIT_AUTH_TOKEN={{env.PAT}}
          
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

